#!/usr/bin/env node
// generate-daily.js — Generate 365 pre-baked daily challenge sets
// Run: node generate-daily.js
// Output: js/daily-challenges.js

// Seeded PRNG (mulberry32) for deterministic generation
function mulberry32(seed) {
  return function() {
    seed |= 0; seed = seed + 0x6D2B79F5 | 0;
    let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

function makeRng(seed) {
  const rng = mulberry32(seed);
  return {
    random: rng,
    randInt: (min, max) => Math.floor(rng() * (max - min + 1)) + min,
    pick: (arr) => arr[Math.floor(rng() * arr.length)],
  };
}

// --- Question generators (mirrors questions.js but with seeded RNG) ---

function genEasyAdd(r) {
  const a = r.randInt(10, 99);
  const b = r.randInt(10, 99);
  return { expression: `${a} + ${b}`, answer: a + b, difficulty: 'easy' };
}

function genEasySub(r) {
  const a = r.randInt(20, 99);
  const b = r.randInt(10, a - 1);
  return { expression: `${a} − ${b}`, answer: a - b, difficulty: 'easy' };
}

function genEasyMul(r) {
  const a = r.randInt(2, 12);
  const b = r.randInt(2, 12);
  return { expression: `${a} × ${b}`, answer: a * b, difficulty: 'easy' };
}

function genMediumAdd(r) {
  const a = r.randInt(100, 999);
  const b = r.randInt(100, 999);
  return { expression: `${a} + ${b}`, answer: a + b, difficulty: 'medium' };
}

function genMediumSub(r) {
  const a = r.randInt(200, 999);
  const b = r.randInt(100, a - 50);
  return { expression: `${a} − ${b}`, answer: a - b, difficulty: 'medium' };
}

function genMediumMul(r) {
  const a = r.randInt(11, 99);
  const b = r.randInt(11, 49);
  return { expression: `${a} × ${b}`, answer: a * b, difficulty: 'medium' };
}

function genHardMul(r) {
  const a = r.randInt(100, 999);
  const b = r.randInt(11, 99);
  return { expression: `${a} × ${b}`, answer: a * b, difficulty: 'hard' };
}

function genHardMultiStep(r) {
  const a = r.randInt(50, 500);
  const b = r.randInt(10, 50);
  const c = r.randInt(100, 999);
  const op = r.pick(['+', '−']);
  const product = a * b;
  const answer = op === '+' ? product + c : product - c;
  return { expression: `${a} × ${b} ${op} ${c}`, answer, difficulty: 'hard' };
}

function genHardLargeAddSub(r) {
  const a = r.randInt(1000, 9999);
  const b = r.randInt(1000, 9999);
  const c = r.randInt(100, 999);
  return { expression: `${a} + ${b} − ${c}`, answer: a + b - c, difficulty: 'hard' };
}

function genExtremeLargeMul(r) {
  const a = r.randInt(100, 9999);
  const b = r.randInt(100, 999);
  return { expression: `${a} × ${b}`, answer: a * b, difficulty: 'extreme' };
}

function genExtremeChained(r) {
  const a = r.randInt(100, 999);
  const b = r.randInt(10, 99);
  const c = r.randInt(10, 99);
  const answer = a * b + c * a;
  return { expression: `${a} × ${b} + ${c} × ${a}`, answer, difficulty: 'extreme' };
}

function genExtremeDivision(r) {
  const divisor = r.randInt(7, 99);
  const rawAnswer = r.randInt(100, 9999);
  const dividend = divisor * rawAnswer + r.randInt(0, divisor - 1);
  const answer = Math.round((dividend / divisor) * 10) / 10;
  return { expression: `${dividend.toLocaleString()} ÷ ${divisor}`, answer, difficulty: 'extreme' };
}

const EASY_GENS = [genEasyAdd, genEasySub, genEasyMul];
const MEDIUM_GENS = [genMediumAdd, genMediumSub, genMediumMul];
const HARD_GENS = [genHardMul, genHardMultiStep, genHardLargeAddSub];
const EXTREME_GENS = [genExtremeLargeMul, genExtremeChained, genExtremeDivision];

// --- Generate 365 daily sets ---

const SEED_BASE = 20260422; // Deterministic seed base
const START_DATE = new Date(2026, 3, 22); // Apr 22, 2026 (launch day)

const challenges = [];

for (let day = 0; day < 365; day++) {
  const date = new Date(START_DATE);
  date.setDate(date.getDate() + day);
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const dd = String(date.getDate()).padStart(2, '0');
  const dateStr = `${yyyy}-${mm}-${dd}`;

  const r = makeRng(SEED_BASE + day);

  // Each daily set: 1 Easy, 2 Medium, 1 Hard, 1 Extreme
  const questions = [
    r.pick(EASY_GENS)(r),
    r.pick(MEDIUM_GENS)(r),
    r.pick(MEDIUM_GENS)(r),
    r.pick(HARD_GENS)(r),
    r.pick(EXTREME_GENS)(r),
  ];

  challenges.push({
    day: day + 1,
    date: dateStr,
    questions: questions.map(q => ({
      expression: q.expression,
      answer: q.answer,
      difficulty: q.difficulty,
    })),
  });
}

// --- Write output ---

const fs = require('fs');
const path = require('path');

const output = `// daily-challenges.js — Auto-generated by generate-daily.js
// 365 daily challenge sets for Math Guessr (Jan 1 - Dec 31, 2026)
// DO NOT EDIT — regenerate with: node generate-daily.js

const DAILY_CHALLENGES = ${JSON.stringify(challenges, null, 2)};
`;

const outPath = path.join(__dirname, 'js', 'daily-challenges.js');
fs.writeFileSync(outPath, output, 'utf8');

console.log(`Generated ${challenges.length} daily challenge sets → ${outPath}`);
console.log(`First day: ${challenges[0].date}, Last day: ${challenges[364].date}`);
console.log(`Sample (Day 1):`, JSON.stringify(challenges[0].questions, null, 2));
